FROM python:alpine3.7
RUN mkdir /cityppl
COPY . /cityppl
WORKDIR /cityppl
RUN python db.py
RUN pip install -r requirements.txt
EXPOSE 5001
RUN export FLASK_APP=api.py
RUN flask run --host=0.0.0.0
ENTRYPOINT [ "python" ]
CMD [ "api.py" ]
