apiVersion: v1
kind: Service
metadata:
  name: flask-app
  labels:
    name: flask-app
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
      targetPort: 5000
      name: http
  selector:
    name: flask-app