apiVersion: v1
kind: Service
metadata:
  name: flaskapi-servic
  labels:
    name: flask-app
spec:
  type: NodePort
  ports:
    - port: 5000
      nodePort: 30080
      name: http
  selector:
    app: flask-app
